package handler

import (
	"fmt"
	"net/http"
	"regexp"
	"time"

	"cyberstrike-ai/internal/config"
	"cyberstrike-ai/internal/database"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// AIChannelPublic deliberately excludes connection settings, credentials and
// arbitrary provider fields. It is safe for model pickers without config:read.
type AIChannelPublic struct {
	Name  string               `json:"name"`
	Model string               `json:"model"`
	Probe AIChannelProbePublic `json:"probe"`
}

type AIChannelProbePublic struct {
	Status   string     `json:"status"`
	Success  bool       `json:"success"`
	Stale    bool       `json:"stale"`
	TTFTMs   *int64     `json:"ttft_ms"`
	TestedAt *time.Time `json:"tested_at,omitempty"`
	Error    string     `json:"error,omitempty"`
}

type AIChannelsPublicResponse struct {
	DefaultChannel  string                     `json:"default_channel"`
	Channels        map[string]AIChannelPublic `json:"channels"`
	ProbesAvailable bool                       `json:"probes_available"`
}

var aiChannelProbeHTTPError = regexp.MustCompile(`^上游返回 HTTP ([1-5][0-9]{2})，请检查模型权限、配额与服务地址$`)

// Only diagnostic messages generated by our probe are published. In particular,
// never relay arbitrary historical/provider errors: even a rotated/deleted key
// or a credential embedded in a URL cannot be reliably redacted after the fact.
func publicAIChannelProbeError(message string) string {
	switch message {
	case "", "配置不完整：请填写 API Key 和模型型号", "测试超时（45 秒），未完成流式响应", "测试已取消",
		"流式连接失败，请检查服务地址、TLS、网络或上游响应格式", "未收到有效文本 token；请确认模型支持流式文本生成":
		return message
	}
	if match := aiChannelProbeHTTPError.FindStringSubmatch(message); match != nil {
		return fmt.Sprintf("上游返回 HTTP %s，请检查模型权限、配额与服务地址", match[1])
	}
	return "测试失败，详细信息请在系统设置中查看"
}

func publicAIChannelProbe(channel config.AIChannelConfig, stored database.AIChannelProbe) AIChannelProbePublic {
	result := AIChannelProbePublic{
		Status: "failed", Success: stored.Success,
		Stale: stored.ConfigHash != aiChannelProbeHash(channel),
		Error: publicAIChannelProbeError(stored.Error),
	}
	if stored.Success {
		result.Status = "ready"
	}
	if result.Stale {
		result.Status = "stale"
	}
	if stored.TTFTMs != nil && *stored.TTFTMs >= 0 {
		ms := *stored.TTFTMs
		result.TTFTMs = &ms
	}
	if !stored.TestedAt.IsZero() {
		testedAt := stored.TestedAt
		result.TestedAt = &testedAt
	}
	return result
}

// GetAIChannels reads persisted probe metadata only; it never calls a model.
// Missing/unavailable probe storage must not prevent choosing a model. Report
// unknown, not untested, when records could not be loaded.
func (h *ConfigHandler) GetAIChannels(c *gin.Context) {
	c.Header("Cache-Control", "no-store")
	stored := map[string]database.AIChannelProbe{}
	available := false
	if h.db != nil {
		var err error
		stored, err = h.db.ListAIChannelProbes()
		available = err == nil
		if err != nil && h.logger != nil {
			h.logger.Warn("读取模型选择器测试记录失败", zap.Error(err))
		}
	}
	h.mu.RLock()
	defer h.mu.RUnlock()
	result := AIChannelsPublicResponse{
		DefaultChannel:  h.config.AI.DefaultChannel,
		Channels:        make(map[string]AIChannelPublic, len(h.config.AI.Channels)),
		ProbesAvailable: available,
	}
	for id, channel := range h.config.AI.Channels {
		probe := AIChannelProbePublic{Status: "unknown"}
		if available {
			probe.Status = "untested"
			if record, ok := stored[id]; ok {
				probe = publicAIChannelProbe(channel, record)
			}
		}
		result.Channels[id] = AIChannelPublic{Name: channel.Name, Model: channel.Model, Probe: probe}
	}
	c.JSON(http.StatusOK, result)
}
